version: "3"
services: 
  mock-idp-1:
    image: ${DOCKER_REPO:-ndidplatform}/mock:${DOCKER_TAG:-latest}
    environment:
        - API_SERVER_ADDRESS=http://api-idp-1:${API_PORT:-8080}
        - NDID_API_CALLBACK_IP=mock-idp-1
        - NDID_API_CALLBACK_PORT=${EXAMPLE_CALLBACK_PORT:-5000}
    command: idp
    ports:
      - "8000:${EXAMPLE_CALLBACK_PORT:-5000}"
    networks:
      - ${DOCKER_REPO:-ndidplatform}
  mock-as:
    image: ${DOCKER_REPO:-ndidplatform}/mock:${DOCKER_TAG:-latest}
    environment:
        - API_SERVER_ADDRESS=http://api-as:${API_PORT:-8080}
        - NDID_API_CALLBACK_IP=mock-as
        - NDID_API_CALLBACK_PORT=${EXAMPLE_CALLBACK_PORT:-5000}
    command: as
    ports:
      - "10000:${EXAMPLE_CALLBACK_PORT:-5000}"
    networks:
      - ${DOCKER_REPO:-ndidplatform}
  mock-rp:
    image: ${DOCKER_REPO:-ndidplatform}/mock:${DOCKER_TAG:-latest}
    environment:
        - API_SERVER_ADDRESS=http://api-rp:${API_PORT:-8080}
        - NDID_API_CALLBACK_IP=mock-rp
        - NDID_API_CALLBACK_PORT=${EXAMPLE_CALLBACK_PORT:-5000}
    command: rp
    ports:
      - "11000:${EXAMPLE_CALLBACK_PORT:-5000}"
    networks:
      - ${DOCKER_REPO:-ndidplatform}
networks:
  ndidplatform:
